language: node_js
sudo: required
before_script:
- npm install -g bower polylint polymer-cli web-component-tester
- bower install
- polylint
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- polymer test
dist: trusty